### ISSUE TITLE
How is this different from Q?

### ISSUE THREAD

**Issue by Masynchin** [kerelape/reikai#1]
What is difference between this library and [Q](https://github.com/kerelape/Q)? What is the motivation to do another package and not continue previous work?

**Comment by kerelape** [comment]
The difference is that this library expects every quantum to be dataizable to bytes only, while Q allows using other types. I am experimenting to find the best approach for OO. At this moment I suppose that in OOP must be no basic types (atoms in EO) but bytes, and a program must only operate these. Once I find what fits OO best I'll release `1.0.0` version of either this or Q.

**Comment by Masynchin** [comment]
> I am experimenting to find the best approach for OOP.

Good luck to find out!
