### ISSUE TITLE
TcpEndpointTests.kt:27: Create adapter for kotlin.String...

### ISSUE THREAD

**Issue by 0pdd** [kerelape/reikai#10]
The puzzle `2-20dd5b0a` from #2 has to be resolved: 

https://github.com/kerelape/reikai/blob/a4ea7f8cc2f9ec4cc99dd99ab225c96646a43735/src/test/kotlin/me/kerelape/reikai/io/network/TcpEndpointTests.kt#L27-L27

The puzzle was created by Киряев Кирилл on 20-Jul-22. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by kerelape** [comment]
@Masynchin don't you want to fix this?

**Comment by Masynchin** [comment]
@kerelape I will try. My task is to add extension function for String same as for Integer?

**Comment by Masynchin** [comment]
> @kerelape I will try. My task is to add extension function for String same as for Integer?

And String (: Entity) object. You escaped name collision of Integer and Number, what should I do in this case? Should I make EntityString or Text, or there is other name?

**Comment by kerelape** [comment]
@Masynchin `Text` would be great, also add the extension

**Comment by 0pdd** [comment]
The puzzle `2-20dd5b0a` has disappeared from the source code, that's why I closed this issue.
