### ISSUE TITLE
`Socket`

### ISSUE THREAD

**Issue by kerelape** [kerelape/reikai#2]
**Describe the bug**
We need something to connect to an endpoint via sockets and communicate with it.

**Expected behavior**
An object that can connect or listen.

**Comment by 0pdd** [comment]
@kerelape 5 puzzles [#10](https://github.com/kerelape/reikai/issues/10), [#6](https://github.com/kerelape/reikai/issues/6), [#7](https://github.com/kerelape/reikai/issues/7), [#8](https://github.com/kerelape/reikai/issues/8), [#9](https://github.com/kerelape/reikai/issues/9) are still not solved.

**Comment by 0pdd** [comment]
@kerelape 4 puzzles [#10](https://github.com/kerelape/reikai/issues/10), [#6](https://github.com/kerelape/reikai/issues/6), [#7](https://github.com/kerelape/reikai/issues/7), [#9](https://github.com/kerelape/reikai/issues/9) are still not solved; solved: [#8](https://github.com/kerelape/reikai/issues/8).

**Comment by 0pdd** [comment]
@kerelape 3 puzzles [#6](https://github.com/kerelape/reikai/issues/6), [#7](https://github.com/kerelape/reikai/issues/7), [#9](https://github.com/kerelape/reikai/issues/9) are still not solved; solved: [#10](https://github.com/kerelape/reikai/issues/10), [#8](https://github.com/kerelape/reikai/issues/8).

**Comment by 0pdd** [comment]
@kerelape 3 puzzles [#21](https://github.com/kerelape/reikai/issues/21), [#6](https://github.com/kerelape/reikai/issues/6), [#7](https://github.com/kerelape/reikai/issues/7) are still not solved; solved: [#10](https://github.com/kerelape/reikai/issues/10), [#8](https://github.com/kerelape/reikai/issues/8), [#9](https://github.com/kerelape/reikai/issues/9).

**Comment by 0pdd** [comment]
@kerelape 2 puzzles [#6](https://github.com/kerelape/reikai/issues/6), [#7](https://github.com/kerelape/reikai/issues/7) are still not solved; solved: [#10](https://github.com/kerelape/reikai/issues/10), [#21](https://github.com/kerelape/reikai/issues/21), [#8](https://github.com/kerelape/reikai/issues/8), [#9](https://github.com/kerelape/reikai/issues/9).

**Comment by 0pdd** [comment]
@kerelape the puzzle [#7](https://github.com/kerelape/reikai/issues/7) is still not solved; solved: [#10](https://github.com/kerelape/reikai/issues/10), [#21](https://github.com/kerelape/reikai/issues/21), [#6](https://github.com/kerelape/reikai/issues/6), [#8](https://github.com/kerelape/reikai/issues/8), [#9](https://github.com/kerelape/reikai/issues/9).

**Comment by 0pdd** [comment]
@kerelape all 6 puzzles are solved here: [#10](https://github.com/kerelape/reikai/issues/10), [#21](https://github.com/kerelape/reikai/issues/21), [#6](https://github.com/kerelape/reikai/issues/6), [#7](https://github.com/kerelape/reikai/issues/7), [#8](https://github.com/kerelape/reikai/issues/8), [#9](https://github.com/kerelape/reikai/issues/9).
