### ISSUE TITLE
Equality for two equal pairs

### ISSUE THREAD

**Issue by Masynchin** [kerelape/reikai#40]
This test fails.

~~~kotlin
@Test
fun `false for two pairs`() = runBlocking {
    Assertions.assertEquals(
        0,
        Equality(
            1.asEntity,
            1.asEntity,
            2.asEntity,
            2.asEntity
        ).dataize()[0]
    )
}
~~~

**Comment by kerelape** [comment]
@Masynchin `Equality` is true only if *all* the elements are same. I think the documentation is poor.

**Comment by Masynchin** [comment]
> `Equality` is true only if _all_ the elements are same.

Then the test should still fail?

**Comment by kerelape** [comment]
@Masynchin I am sorry, I miss understood the test. This is a bug.

**Comment by kerelape** [comment]
This can be fixed by replacing `vararg` with two arguments, and adding an `And` class.

**Comment by Masynchin** [comment]
> This can be fixed by replacing `vararg` with two arguments, and adding an `And` class.

If Equality will accept only two arguments, then we can still use `Xor`.

**Comment by kerelape** [comment]
@Masynchin `And` is require for chaining: `And(Equality(...), True)`

**Comment by Masynchin** [comment]
> @Masynchin `And` is required for chaining: `And(Equality(...), True)`

Recursion? Or is not about Equality?

**Comment by kerelape** [comment]
@Masynchin a useful object for logical checks, since it's not possible to check multiple object for equality now — there must be way to still check.

**Comment by Masynchin** [comment]
> Since it's not possible to check multiple object for equality now — there must be way to still check.

What do you think about this?

~~~kotlin
class EqualMany(first: Entity, vararg others: Entity) {
    others.all { Equality(first, it).toBoolean() }.asEntity()
}
~~~

**Comment by kerelape** [comment]
@Masynchin I think we may add object like `Some` and `Every`:
```kotlin
Some(False, False, True) // dataizes to true, because one of the given is True

Every(True, True, False) // dataizes to false, because not each of the given is True
```

And then use `Equality` inside them
