### ISSUE TITLE
Improve `Equality` tests

### ISSUE THREAD

**Issue by kerelape** [kerelape/reikai#42]
@Masynchin looks like it won't work if an element of `Xor` is longer than 1 byte.

_Originally posted by @kerelape in https://github.com/kerelape/reikai/issues/39#issuecomment-1193277230_

Test with differently long objects.

Context: expected behaviour for boolean object is that `0` (any length in bytes) is `false` and everything that is not `0` is `true`. Note that a boolean can be any size, this is why we have to compare them using `BigInteger`.

**Comment by kerelape** [comment]
@Masynchin can you help with this?

**Comment by kerelape** [comment]
Also the tests must be fixed, because they are not right. If `Equality` is an integer like this `00_00_00_01`, then, however, the tests will treat it as `false`. This behaviour is not correct

**Comment by Masynchin** [comment]
> `0` (any length in bytes) is `false`

So, `byteArrayOf(0, 0, 0, 0)` is false?

**Comment by kerelape** [comment]
> > `0` (any length in bytes) is `false`
> 
> So, `byteArrayOf(0, 0, 0, 0)` is false?

@Masynchin yes and if any of those bytes is not `0`, it's true

**Comment by Masynchin** [comment]
> @Masynchin can you help with this?

Will be available by about 2022-07-24T15:00:00+0000.

**Comment by kerelape** [comment]
@Masynchin note that the package name has changed to `io.github.kerelape.reikai`
