### ISSUE TITLE
`Empty`

### ISSUE THREAD

**Issue by kerelape** [kerelape/reikai#50]
**Describe the bug**
When trying to perform a logical operation on `Empty`, `BigInteger` throws an exception.

**Expected behavior**
`Empty` must be treated like `False`

**Comment by Masynchin** [comment]
What about to add `Entity#asInt`? It will allow to fix this, but will bring another knowledge of higher type to Entity.

**Comment by kerelape** [comment]
@Masynchin I think we can add a check for this failure into `toBoolean` and return `False` object in case the exception occurs

**Comment by Masynchin** [comment]
> @Masynchin I think we can add a check for this failure into `toBoolean` and return `False` object in case the exception occurs

Seems legit.
