### ISSUE TITLE
Break down to modules

### ISSUE THREAD

**Issue by kerelape** [kerelape/reikai#58]
There must be separated modules for `core`, `io`, `math`, `logic`, and `text`.

Name of the `core` modules must be `io.github.kerelape.reikai` (without `core`).

**Comment by Masynchin** [comment]
> There must be separated modules for `core`, `io`, `math`, `logic`, and `text`.

What does it mean?

**Comment by kerelape** [comment]
> > There must be separated modules for `core`, `io`, `math`, `logic`, and `text`.
> 
> What does it mean?

Different artifacts for each module

**Comment by Masynchin** [comment]
>  > There must be separated modules for `core`, `io`, `math`, `logic`, and `text`.
> Different artifacts for each module

How it can be done? I am not so familiar with Java/Kotlin, Maven, and its artifacts system. Can you explain?

**Comment by kerelape** [comment]
@Masynchin you can see [this](https://github.com/objectionary/eo) repository, it uses the system

**Comment by kerelape** [comment]
@Masynchin well, I think this can wait
