### ISSUE TITLE
Binary objects

### ISSUE THREAD

**Issue by kerelape** [kerelape/reikai#59]
Move `Xor` and `Not` to `io.github.kerelape.reikai.binary`

**Comment by kerelape** [comment]
Also add other binary objects: `And` and `Or`

**Comment by Masynchin** [comment]
@kerelape can I do it?

**Comment by kerelape** [comment]
@Masynchin it's yours

**Comment by Masynchin** [comment]
@kerelape should we update `@since` annotation since they are moved to the new module?

**Comment by kerelape** [comment]
> @kerelape should we update `@since` annotation since they are moved to the new module?

@Masynchin I don't think so
