### ISSUE TITLE
`Some` and `Every`

### ISSUE THREAD

**Issue by kerelape** [kerelape/reikai#68]
@Masynchin I think we may add object like `Some` and `Every`:
```kotlin
Some(False, False, True) // dataizes to true, because one of the given is True

Every(True, True, False) // dataizes to false, because not each of the given is True
```

And then use `Equality` inside them

_Originally posted by @kerelape in https://github.com/kerelape/reikai/issues/40#issuecomment-1197637744_

**Comment by Masynchin** [comment]
@kerelape assign me!

**Comment by Masynchin** [comment]
> And then use `Equality` inside them

In this example we can use `all { it.dataize().asBoolean }`. Maybe you thought that we can use them inside EqualMany object?

**Comment by kerelape** [comment]
> Maybe you thought that we can use them inside EqualMany object?

`EqualMany` seems redundant in case we have these objects. The expected behaviour is:
```kotlin
Every(
    Identity(Text("abc"), Text("abc")),
    Identity(1.asEntity, 1.asEntity)
).toBoolean() // true
```

**Comment by Masynchin** [comment]
> `EqualMany` seems redundant in case we have these objects. The expected behaviour is:
> 
> ```kotlin
> Every(
>     Identity(Text("abc"), Text("abc")),
>     Identity(1.asEntity, 1.asEntity)
> ).toBoolean() // true
> ```

But Every (And) checks Boolean Entity, rather than compares Entities. For me EqualMany is fixed Equality, so it can be used like `EqualMany(1.asEntity, 1.asEntity, 1.asEntity)`.

**Comment by kerelape** [comment]
@Masynchin I don't like the name, "EqualMany", as well as any kind of "equal". Because we check for identity of data behind the object, but not equality of the object to another object. Well, I agree that this: `SomethingMany(obj1, obj2, obj3)` is better than `Every(Identity(obj1, obj2), Identity(obj1, obj3))`, but we'd need to find a better way to call it, but not "*Many". Maybe "All", or "Same", or something else (better something else).

When these objects are done, the implementation of this one would be as simple as:
```kotlin
class EqualMany(vararg items: Entity) : EntityWrap(Every(items.reduce(::Identity)))
```

**Comment by Masynchin** [comment]
> Maybe "All", or "Same", or something else (better something else).

What do you think about Identical?

**Comment by Masynchin** [comment]
@kerelape what should Some and Every dataizes for when no arguments passed?

**Comment by kerelape** [comment]
> > Maybe "All", or "Same", or something else (better something else).
> 
> What do you think about Identical?

Sounds good

**Comment by kerelape** [comment]
> @kerelape what should Some and Every dataizes for when no arguments passed?

@Masynchin throw an `IllegalStateException` if there is less than one argument

**Comment by Masynchin** [comment]
@kerelape close (I forgor to mention this issue in my PR 💀)
