### ISSUE TITLE
Add `Strict` typing

### ISSUE THREAD

**Issue by kerelape** [kerelape/reikai#71]
I think it would be useful to have a tool to warn that a class is used incorrectly, like in this example: 
```kotlin
ContentLength(Text("128"))
```

We may add an annotation for parameters and classes to describe their type of data. However these can be omitted.

For checking we can add a ktlint (or kapt) check.

**Comment by 0pdd** [comment]
@kerelape the puzzle [#73](https://github.com/kerelape/reikai/issues/73) is still not solved.

**Comment by 0pdd** [comment]
@kerelape the puzzle [#unknown]() is still not solved.

**Comment by Masynchin** [comment]
> We may add an annotation for parameters and classes to describe their type of data.

> (From README) The idea is that there is no data types — the only data type is ByteArray, an arbitrary length amount of bytes. And the objects manipulate the bytes.

@kerelape 🤨?

**Comment by kerelape** [comment]
> > We may add an annotation for parameters and classes to describe their type of data.
> 
> > (From README) The idea is that there is no data types — the only data type is ByteArray, an arbitrary length amount of bytes. And the objects manipulate the bytes.
> 
> @kerelape 🤨?

@Masynchin I understand. This is not an accepted feature. But I think, this would be better to have typing like in JS (via JsDoc) where you, anyway, can pass an int where a string is expected, but this will be highlighted like 'unexpected' (not wrong!).

**Comment by 0pdd** [comment]
@kerelape the only puzzle [#unknown]() is solved here.
