### ISSUE TITLE
Strict.kt:6-7: Create a ktlint check. This check will...

### ISSUE THREAD

**Issue by 0pdd** [kerelape/reikai#73]
The puzzle `71-1172cb3f` from #71 has to be resolved: 

https://github.com/kerelape/reikai/blob/92b803be4bc7848fb7a866e94afac1177b39fe49/src/main/kotlin/io/github/kerelape/reikai/typing/Strict.kt#L6-L7

The puzzle was created by Киряев Кирилл on 28-Jul-22. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by kerelape** [comment]
Or kapt
