### ISSUE TITLE
Docs theme

### ISSUE THREAD

**Issue by Masynchin** [kerelape/reikai#87]
[Current](https://github.com/kerelape/reikai/commit/0c78224b2be27bb1f6d9417b2a53c5ba56a8ddbe) docs theme is cringe. 👎🏻

**Comment by kerelape** [comment]
@Masynchin any suggestions?

**Comment by Masynchin** [comment]
> @Masynchin any suggestions?

Not yet, will search.

**Comment by Masynchin** [comment]
I searched for "docs" theme, and found [this one](https://github.com/just-the-docs/just-the-docs) the most clear. It is also has a built-in search!

**Comment by kerelape** [comment]
@Masynchin looks great! apply it.
